export class HomeConstants{
  /**
   * Swiper item space.
   */
  static readonly SWIPER_ITEM_SPACE: string = '14vp';
  /**
   * Banner aspect ratio list.
   */
  static readonly BANNER_RATIOS: number[] = [1.5, 1.83, 2.33];
  /**
   * Menu grid margin.
   */
  static readonly MENU_GRID_MARGIN: number[] = [32, 48, 64];
  /**
   * 首页排行榜歌曲宽高比例
   */
  static readonly HOME_RANKING_GRID_RATIO: number = 1;
  /**
   * 首页MV图片宽高比
   */
  static readonly HOME_MV_RATIO: number = 2;
  /**
   * 首页导航栏的宽度。只有LG
   */
  static readonly HOME_NAVIGATION_WIDTH_LG: number = 96;
  /**
   * 首页底部空布局
   */
  static readonly HOME_EMPTY_VIEW_HEIGHT: number = 30;
  /**
   * 首页排行榜歌单的圆角。
   */
  static readonly HOME_TOP_CHARTS_RADIUS: number = 16;
  /**
   * 首页排行榜Item Row间距
   */
  static readonly HOME_TOP_CHARTS_ROW_SPACE: number = 14;
  /**
   * 首页标题与列表间距
   */
  static readonly HOME_TITLE_LIST_SPACE: number = 16;
  /**
   * 首页排行榜列表间距
   */
  static readonly HOME_TOP_CHARTS_LIST_SPACE: number = 12;
  /**
   * 首页MV列数
   */
  static readonly HOME_MV_COLUMNS: number[] = [4, 2, 1];
  /**
   * 首页MV Item Row 间距
   */
  static readonly HOME_MV_ROW_SPACE: number = 10;
  /**
   * 首页MV Grid 间距
   */
  static readonly HOME_MV_GRID_GAP: number = 15;
  /**
   * 首页MV 标题和副标题间距
   */
  static readonly HOME_MV_TITLE_SUB_SPACE: number = 2;
  /**
   * Banner text letter space list.
   */
  static readonly BANNER_TEXT_LETTER_SPACES: string[] = ['3vp', '1vp'];
}