export class CommonConstants {
  /**
   * Current Breakpoint
   */
  static readonly CURRENT_BREAKPOINT: string = 'currentBreakpoint';
  /**
   * Navigation stack
   */
  static readonly PATH_STACK: string = 'pathStack';
  /**
   * Window width
   */
  static readonly WINDOW_WIDTH: string = 'windowWidth';
  /**
   * Status bar height
   */
  static readonly STATUS_BAR_HEIGHT: string = 'statusBarHeight';
  /**
   * Nav bar height
   */
  static readonly NAV_BAR_HEIGHT: string = 'navBarHeight';
  /**
   * Player Detail cover rotate angle
   */
  static readonly COVER_ROTATE_ANGLE: string = 'coverRotateAngle';
  /**
   * Song list
   */
  static readonly SONG_LIST: string = 'songList';
  /**
   * Context
   */
  static readonly CONTEXT: string = 'context';
  /**
   * Media service
   */
  static readonly MEDIA_SERVICE: string = 'mediaService';
  /**
   * Current time
   */
  static readonly CURRENT_TIME: string = 'currentTime';
  /**
   * Progress
   */
  static readonly PROGRESS: string = 'progress';
  /**
   * Total time
   */
  static readonly TOTAL_TIME: string = 'totalTime';
  /**
   * Progress max
   */
  static readonly PROGRESS_MAX: string = 'progressMax';
  /**
   * Is play
   */
  static readonly IS_PLAY: string = 'isPlay';
  /**
   * Select index
   */
  static readonly SELECT_INDEX: string = 'selectIndex';
  /**
   * VOLUME
   */
  static readonly VOLUME: string = 'volume';
  /**
   * PLAY_MODE
   */
  static readonly PLAY_MODE: string = 'playMode';
  /**
   * Shared song cover
   */
  static readonly SHARED_COVER_IMG: string = 'sharedSongCover';
  /**
   * Update time of av player.
   */
  static readonly AV_PLAYER_UPDATE_TIME: string = 'av_updateTime';

  /**
   * Current time of av player.
   */
  static readonly AV_PLAYER_CURRENT_TIME: string = 'av_currentTime';

  /**
   * Total time of av player.
   */
  static readonly AV_PLAYER_TOTAL_TIME: string = 'av_totalTime';

  /**
   * Progress of av player.
   */
  static readonly AV_PLAYER_PROGRESS: string = 'av_progress';
  /**
   * The form id is no exit.
   */
  static readonly ID_NO_EXIT: number = 16501001;
  /**
   * Search icon content margin
   */
  static readonly SEARCH_ICON_CONTENT_MARGIN: string = '15vp';
  /**
   * Window util.
   */
  static readonly WINDOW_UTIL: string = 'windowUtil';
  /**
   * X component surface width.
   */
  static readonly X_COMPONENT_SURFACE_WIDTH: number = 1920;

  /**
   * X component surface height.
   */
  static readonly X_COMPONENT_SURFACE_HEIGHT: number = 1080;
  /**
   * Video aspect ratio.
   */
  static readonly VIDEO_ASPECT_RATIO: number = 1.78;
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';
  static readonly VIDEO_GRID_COLUMNS: string = '1fr 1fr';
  /**
   * Device types.
   */
  static readonly DEVICE_TYPES: string[] = ['2in1', 'tablet', 'phone'];
  /**
   * Text opacity.
   */
  static readonly TEXT_OPACITY: number[] = [0.4, 0.5, 0.6, 1, 0.8];
  /**
   * Divider opacity.
   */
  static readonly DIVIDER_OPACITY: number = 0.05;
  /**
   * List space.
   */
  static readonly LIST_SPACE: string = '12vp';
}


